<?php

return [
    'tour' => [
        'maxlength_description' => 1000 * 5,
        'maxlength_name' => 255,
        'minlength_name' => 3,
        'maxlength_content' => 2000,
        'maxsize_thumbnail' => 10 * 1024,
        'max_price' => 10000 * 2,
        'min_price' => 1,
        'min_guess' => 1,
        'max_guess' => 200,
        'min_day_active' => 1,
        'max_day_active' => 60,
        'deadline' => 5,
    ],
    'booking' => [
        'adult' => 'adult',
        'children' => 'children',
    ],
    'hotel' => [
        'maxlength_name' => 80,
        'minlength_name' => 3,
        'maxlength_address' => 255,
        'length_phone' => 10,
    ],
    'parent_id' => 0,
    'password_test' => '123456',
    'footer_logo' => '/templates/bookingtour/img/logo-color-sm.png',
    'tour_default_img' => '/templates/bookingtour/img/tour_img_default.jpg',
    'date_upload_folder' => '/uploads/dates/',
    'service_upload_folder' => '/uploads/services/',
    'date_default_img' => '/templates/bookingtour/img/date_default_img.png',
    'food_default_img' => '/templates/bookingtour/img/food_default_img.jpg',
    'place_default_img' => '/templates/bookingtour/img/place_default_img.jpg',
    'avatar_upload_folder' => '/uploads/avatars/',
    'avatar_default_img' => '/templates/bookingtour/img/avatar_default_img.jpg',
    'booking_cancel' => 0,
    'booking_wait_confirm' => 1,
    'booking_confirmed' => 2,
    'booking_paymented' => 3,
    'booking_finished' => 4,
    'deadline_confirm_minutes' => 1440,
    'paymented_default_value' => 0,
    'times_payment_small' => 1,
    'times_payment_medium' => 2,
    'times_payment_big' => 3,
    'total_cost_small' => 500,
    'total_cost_medium' => 1000,
    'logo-page' => '/templates/bookingtour/img/logo-color-big.png',
    'tour_upload_folder' => '/uploads/tours/',
    'master_card_icon' => '/templates/bookingtour/img/booking/master-card.jpg',
    'discover_icon' => '/templates/bookingtour/img/booking/discover.jpg',
    'visa_icon' => '/templates/bookingtour/img/booking/visa.jpg',
    'paypal_icon' => '/templates/bookingtour/img/booking/paypal.jpg',
    'deadline_booking_minutes' => 5 * 1440,
    'logo_small' => '/templates/bookingtour/img/favicon.png',
    'new_tour_show' => 5,
    'popular_tour_show' => 6,
    'category_tour_show' => 6,
    'news_random_show' => 3,
    'news_upload_folder' => '/uploads/news/',
    'news_default_img' => '/templates/bookingtour/img/news_default_img.jpg',
    'booking_all' => 5,
    'paginate_default_val' => 10,
    'import_success_default_val' => 0,
    'price_search_1_val' => 1,
    'price_search_2_val' => 2,
    'price_search_3_val' => 3,
    'price_search_4_val' => 4,
    'category_show_paginate' => 5,
    'avatar_extension' => '.jpg',
    '404_img' => '/templates/bookingtour/img/not-found.png',
];
