<?php

return [
    'parent_id' => 0,
    'password_test' => 'secret',
    'footer_logo' => '/templates/bookingtour/img/logo-color-sm.png',
    'tour_default_img' => '/templates/bookingtour/img/tour_img_default.jpg',
    'date_upload_folder' => '/uploads/dates/',
    'service_upload_folder' => '/uploads/services/',
    'date_default_img' => '/templates/bookingtour/img/date_default_img.png',
    'food_default_img' => '/templates/bookingtour/img/food_default_img.jpg',
    'place_default_img' => '/templates/bookingtour/img/place_default_img.jpg',
    'avatar_upload_folder' => '/uploads/avatars/',
    'avatar_default_img' => '/templates/bookingtour/img/avatar_default_img.jpg',
    'booking_cancel' => 0,
    'booking_wait_confirm' => 1,
    'booking_confirmed' => 2,
    'booking_paymented' => 3,
    'booking_finished' => 4,
    'deadline_confirm_minutes' => 1440,
    'paymented_default_value' => 0,
    'times_payment_small' => 1,
    'times_payment_medium' => 2,
    'times_payment_big' => 3,
    'total_cost_small' => 500,
    'total_cost_medium' => 1000,
    'logo-page' => '/templates/bookingtour/img/logo-color-big.png',
    'tour_upload_folder' => '/uploads/tours/',
    'master_card_icon' => '/templates/bookingtour/img/booking/master-card.jpg',
    'discover_icon' => '/templates/bookingtour/img/booking/discover.jpg',
    'visa_icon' => '/templates/bookingtour/img/booking/visa.jpg',
    'paypal_icon' => '/templates/bookingtour/img/booking/paypal.jpg',
    'deadline_booking_minutes' => 5 * 1440,
    'logo_small' => '/templates/bookingtour/img/favicon.png',
];
